### ISSUE TITLE
Incorrect Base URL: docs.smith.langchain -> api.smith.langchain

### ISSUE THREAD

**Issue by jase-k** [langchain-ai/langsmith-docs#121]
In your documentation, you've listed the wrong baseurl: 
![image](https://github.com/langchain-ai/langsmith-docs/assets/46328422/fcc040a9-b8f7-4e85-8a04-4b923c965de7)

When I change to https://api.smith.langchain.com/api/v1/sessions it works. 

If I use: https://docs.smith.langchain.com/api/v1/sessions I get a 404 error.

**Comment by hinthornw** [comment]
Thanks for raising! Should be resolved now
