### ISSUE TITLE
Custom Run IDs & tags with proxy

### ISSUE THREAD

**Issue by sfuller14** [langchain-ai/langsmith-docs#142]
Hi there,

Thanks for all the innovative stuff the team is putting out.

I'm using the langsmith proxy because I need langsmith to support streaming, and, to my understanding of the docs, using the proxy is the only way to do this currently (?).

However, when using the proxy, there's no documentation on how to specify custom Run IDs, Trace IDs, tags, metadata, etc. The pattern shown in [the docs](https://docs.smith.langchain.com/proxy/quickstart#what-is-the-langsmith-proxy) is basically just raw OpenAI API syntax with the proxy URL specified as a param in openai.Client(). 

Are tags, IDs currently supported by the proxy?

Tyia

**Comment by hinthornw** [comment]
Hi @sfuller14 could you elaborate on langsmith not supporting streaming? What are you trying to do?

LangSmith supports streaming natively:

```python
from langsmith import traceable

@traceable
def foo():
    for i in range(10):
        yield i

list(foo)
```

**Comment by sfuller14** [comment]
Okay thanks for confirming. I couldn't find that pattern anywhere in the docs except in the proxy section - could be worth making explicit somewhere like the QuickStart (though I may have just missed it). Thanks!
