### ISSUE TITLE
DOC: <Issue related to /concepts/tracing>

### ISSUE THREAD

**Issue by tedsecretsource** [langchain-ai/langsmith-docs#267]
Does this mean that after 400 days links to traces from experiments will return 404? Is there any way to retain traces beyond 400 days while still being able to use all of LangSmith's features?

**Comment by hinthornw** [comment]
Thanks for the question! I've forward this to the person in charge of this. Feel free to @ me if they don't follow up here in a reasonable timeframe.

**Comment by hinthornw** [comment]
Not at present
