### ISSUE TITLE
DOC: <Issue related to /how_to_guides/setup/set_up_billing>

### ISSUE THREAD

**Issue by MANOJMASHATTI2** [langchain-ai/langsmith-docs#288]
![Langsmith](https://github.com/langchain-ai/langsmith-docs/assets/133615515/3bc89708-6ae9-4b91-8c0f-3cef3406d08c)
I am unable to setup billing option to set up my account can someone help

**Comment by hinthornw** [comment]
Hi @MANOJMASHATTI2 can you write in to support@langchain.dev? We can better help you from there.
