### ISSUE TITLE
Support my own judge model? --custom judge model

### ISSUE THREAD

**Issue by aiyinyuedejustin** [langchain-ai/langsmith-docs#342]
Hi there,
I am wondering does the llm-as-a-judge evaluation from LangSmith support customized my own model as a judge? 
I wish to develop my custom prompts for my own judge model through langsmith. 

I see currently there are only OpenAI models supported.

**Comment by hinthornw** [comment]
It supports any llm you'd like, though we mostly benchmarked OAI/Anthropic/Gemini when we wrote the off-the-shelf prompts
