### ISSUE TITLE
os.environ["LANGCHAIN_TRACING_V2"] = "true" causes AttributeError: '_UnixSelectorEventLoop' object has no attribute '_closed'

### ISSUE THREAD

**Issue by bhs1** [langchain-ai/langsmith-docs#363]
Anyone else seen this? When I set os.environ["LANGCHAIN_TRACING_V2"] = "false" it goes away. I'm using asyncio.run().

**Comment by bhs1** [comment]
Running this guy's code reproduces the issue https://github.com/Kevin7744/Web-Voyager-Using-Langchain/blob/main/main.py#L42

**Comment by mlcocdav** [comment]
Same problem here.

**Comment by hinthornw** [comment]
do you have a stack trace?
