### ISSUE TITLE
DOC: <Issue related to /how_to_guides/monitoring/use_monitoring_charts>

### ISSUE THREAD

**Issue by GuillermoGaete** [langchain-ai/langsmith-docs#381]
Hello! We are Langsmith users and I wanted to know why I can't filter by the name of the run? I also can't do it by the model name. Initially, this could be done, but now the option no longer appears for me.

**Comment by hinthornw** [comment]
Still there: https://docs.smith.langchain.com/how_to_guides/tracing/export_traces#list-all-runs-called-extractor-whose-root-of-the-trace-was-assigned-feedback-user_score-score-of-1
