### ISSUE TITLE
Playground mode does not generate response.

### ISSUE THREAD

**Issue by georgetok** [langchain-ai/langsmith-docs#393]
The error:
Error: Trying to load an object that doesn't implement serialization: $.kwargs.last.kwargs.bound.kwargs.http_client -> {"id":["httpx","AsyncClient"],"lc":1,"repr":"<httpx.AsyncClient object at 0x7f4033d5c970>","type":"not_implemented"}

The prompt used:
System: Do what user asks
Human: Write hello

**Comment by hinthornw** [comment]
Could you share a reproducible example?

**Comment by hinthornw** [comment]
Will re-open if we have more informaiton
