### ISSUE TITLE
how to access expected output in evaluation prompts

### ISSUE THREAD

**Issue by munterwexi** [langchain-ai/langsmith-docs#409]
I want to use a hallucination evaluator on my dataset, which is kv-structured. however there is no way in the ui, to access the expected output or expected output variables? please help

<img width="1962" alt="Bildschirmfoto 2024-08-26 um 21 25 28" src="https://github.com/user-attachments/assets/1eb20fe7-11a1-45aa-9fb6-b6aedfa1f33b">

expected behaviour: access input with input. and output with output. accessors is possible for kv datasets, otherwise evaluation is not possible

**Comment by hinthornw** [comment]
Use `reference.<key-name>`
