### ISSUE TITLE
DOC: <Issue related to /self_hosting/configuration/sso>

### ISSUE THREAD

**Issue by khaerulumam42** [langchain-ai/langsmith-docs#416]
Hi Team,

thank you for creating amazing product! 

Our company use langsmith to monitoring our LLM performance. To improve our security we need to able login using SSO, but we don't have manpower to maintain and deploy self hosted langsmith. 

Is there any plan to add login using SSO in cloud version?

thank you

**Comment by hinthornw** [comment]
Ya starting to roll out now to enterprise customers. If you are interestd in enterprise cloud, please email suport@langchain.dev to request access

**Comment by hinthornw** [comment]
https://docs.smith.langchain.com/how_to_guides/setup/set_up_saml_sso
