### ISSUE TITLE
DOC: <Issue related to how tags are displayed on dashboard>

### ISSUE THREAD

**Issue by andrebeu** [langchain-ai/langsmith-docs#432]
![image](https://github.com/user-attachments/assets/ef3c77d7-7422-40da-bbc2-1884723571a7)

notice tag `n=0` shows under tags column, but not next to the relevant trace in on my runtree. for an example behavior that is working see the gpt-4o-mini tag on the ChatOpenAi trace.

**Comment by vowelparrot** [comment]
If you click "stats" there on the trace does it still not show up? I think we restrict the number of tags that will be rendered by default
