### ISSUE TITLE
DOC: <Issue related to /self_hosting/installation/kubernetes> broken link on langchain homepage 

### ISSUE THREAD

**Issue by LordSyd** [langchain-ai/langsmith-docs#442]
Hello,

the link given on the homepage under the pricing FAQ section for "Where is my data stored?" for self hosting langsmith is wrong. It should be https://docs.smith.langchain.com/self_hosting/installation/kubernetes but is https://docs.smith.langchain.com/self_hosting/kubernetes

The chatbot luckily was very helpful in locating the correct page.

Regards,
Daniel

**Comment by hinthornw** [comment]
Thank you for reporting! should be fixed now. Appreciate that you filed the ticket :)
