### ISSUE TITLE
DOC: <Issue related to /old/cookbook/testing-examples/ragas>

### ISSUE THREAD

**Issue by roy29fuku** [langchain-ai/langsmith-docs#509]
Both links are not working.

> View the evaluation results for project 'back-bibliography-2' at: https://smith.langchain.com/o/ebbaf2eb-769b-4505-aca2-d11de10372a4/datasets/e468392e-e369-4066-99d4-dd05e186e992/compare?selectedSessions=bf005eaa-498d-47f7-a752-4bd260000c23
> View all tests for Dataset BaseCamp Q&A at: https://smith.langchain.com/o/ebbaf2eb-769b-4505-aca2-d11de10372a4/datasets/e468392e-e369-4066-99d4-dd05e186e992 [-> ] 1/21

**Comment by hinthornw** [comment]
Out of curiosity, how did you find yourself on the  /old/ docs?

**Comment by roy29fuku** [comment]
Sorry, I missed the "outdated documentation".
I searched for ‘langsmith rag evaluation’ on Google and found it.
