### ISSUE TITLE
Can't run any prompt in playground without openai key

### ISSUE THREAD

**Issue by Songnianz** [langchain-ai/langsmith-docs#526]
Have you changed the OpenAI key to compulsory in playground recently? 

I can't run any prompt without entering openai key! 

If it's for the new canvas function, there should be a way to bypass or disable it. 

There should be a way for people who only use azure/aws/google/claude to use LangSmith.

**Comment by hinthornw** [comment]
You pick the model for a given prompt. It may be defaulting to openai in your case
![image](https://github.com/user-attachments/assets/690366f8-4284-4526-842c-8bbda06b10e2)

**Comment by Songnianz** [comment]
> You pick the model for a given prompt. It may be defaulting to openai in your case ![image](https://private-user-images.githubusercontent.com/13333726/385942440-690366f8-4284-4526-842c-8bbda06b10e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMTQ2NDIsIm5iZiI6MTczMjAxNDM0MiwicGF0aCI6Ii8xMzMzMzcyNi8zODU5NDI0NDAtNjkwMzY2ZjgtNDI4NC00NTI2LTg0MmMtOGJiZGEwNmIxMGUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDExMDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNDQ3NmVmN2UxZGJlNmI0NGM5ZmFmMzEyMWJmNjBmYzc1N2E1NmFhNmMxMjllNTMzMjFhYzhjMWNmMDI4ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2rV-nFEU5ukANyDRv3iuXkYvZkC7kubuabgVEI3IFqA)

I know, I've been using bedrock for a long while, but last week the openai key become compulsory when I use bedrock. Please see this pic

![image](https://github.com/user-attachments/assets/8fcf566d-411b-4f92-ae0d-828f85cb14af)
