### ISSUE TITLE
Can't run any prompt in playground without openai key

### ISSUE THREAD

**Issue by Songnianz** [langchain-ai/langsmith-docs#541]
I've been using bedrock in playground for a long while, but last week the openai key become compulsory when I use bedrock. There should be a way for people who only use one provider to use langchain. Please see this pic

![image](https://github.com/user-attachments/assets/8fcf566d-411b-4f92-ae0d-828f85cb14af)

_Originally posted by @Songnianz in https://github.com/langchain-ai/langsmith-docs/issues/526#issuecomment-2485410587_

**Comment by hinthornw** [comment]
Flagged to he team member
